:toc: right
:backend: pdf
:doctitle: Living Documentation
:doctype: book
:icons: font
:numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: highlightjs
:toclevels: 3

= *Living Documentation*

include::/home/rmpestano/projects/dbunit-rules/cdi/target/test-classes/cukedoctor-intro.adoc[leveloffset=+1]

== *Summary*
[cols="12*^m", options="header,footer"]
|===
3+|Scenarios 7+|Steps 2+|Features: 1

|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status

12+^|*<<Seeding-database>>*
|1
|0
|1
|4
|0
|0
|0
|0
|0
|4
|05s 686ms
|[green]#*passed*#
12+^|*Totals*
|1|0|1|4|0|0|0|0|0|4 2+|05s 686ms
|===

== *Features*

[[Seeding-database, Seeding database]]
=== *Seeding database*

==== Scenario: Seed database using dbunit CDI
DBUnit CDI integration is done through a https://docs.jboss.org/weld/reference/latest/en-US/html_single/#interceptors[CDI interceptor^].

[IMPORTANT]
=====
CDI must be enabled in your test, see the following example:

[source, java]
----
@RunWith(CdiTestRunner.class) <1>
public class DBUnitCDITest {

}
----
<1> https://deltaspike.apache.org/documentation/test-control.html[CdiTestRunner^] is provided by https://deltaspike.apache.org[Apache Deltaspike^] but you should be able to use other CDI test runners.
=====

****
Given ::
=====
DBUnit interceptor is enabled in your test beans.xml: icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 767ms)#
******

[discrete]
.src/test/resources/META-INF/beans.xml
[discrete]
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://java.sun.com/xml/ns/javaee"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">
     <interceptors>
            <class>com.github.dbunit.rules.cdi.DBUnitInterceptor</class>
     </interceptors>
</beans>
----


******

=====
And ::
=====
The following dataset located at src/test/resources/datasets/users.yml: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

user:
- id: 1
  name: "@realpestano"
- id: 2
  name: "@dbunit"
tweet:
- id: abcdef12345
  content: "dbunit rules!"
  user_id: 1
- id: abcdef12233
  content: "dbunit rules!"
  user_id: 2
- id: abcdef1343
  content: "CDI for the win!"
  user_id: 2
follower:
- id: 1
  user_id: 1
  follower_id: 2

----
=====
When ::
=====
The following test is executed: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[source,java]
----
include::../../src/test/java/com/github/dbunit/rules/DBUnitCDITest.java[tags=seedDatabase]
----


******

=====
Then ::
=====
The database should be seeded with the dataset content icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 918ms)#
=====
****

