:toc: center
:backend: pdf
:doctitle: Living Documentation
:doctype: book
:icons: font
:numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: highlightjs
:toclevels: 3
:revnumber: 0.6.2-SNAPSHOT
:hardbreaks:

= *Living Documentation*

include::/home/travis/build/rmpestano/dbunit-rules/cdi/target/test-classes/cukedoctor-intro.adoc[leveloffset=+1]

== *Summary*
[cols="12*^m", options="header,footer"]
|===
3+|Scenarios 7+|Steps 2+|Features: 3

|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status

12+^|*<<Manage-database-with-DBUnit-Rules-Core>>*
|1
|0
|1
|4
|0
|0
|0
|0
|0
|4
|001ms
|[green]#*passed*#

12+^|*<<Manage-database-with-DBUnit-Rules-CDI>>*
|1
|0
|1
|4
|0
|0
|0
|0
|0
|4
|634ms
|[green]#*passed*#

12+^|*<<Dynamic-data-using-scritable-datasets>>*
|2
|0
|2
|7
|0
|0
|0
|0
|0
|7
|005ms
|[green]#*passed*#
12+^|*Totals*
|4|0|4|15|0|0|0|0|0|15 2+|642ms
|===

== *Features*

[[Manage-database-with-DBUnit-Rules-Core, Manage database with DBUnit Rules Core]]
=== *Manage database with DBUnit Rules Core*

****
====
[quote]
____
In order to manage database state in JUnit tests
As a developer
I want to use DBUnit in my tests.
____
====

DBUnit Rules Core module brings http://dbunit.sourceforge.net/[DBunit^] to your unit tests via https://github.com/junit-team/junit4/wiki/Rules[JUnit rules^].
****

==== Scenario: Seed database using yml dataset

****
Given ::
=====
The following junit rules icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
******

[discrete]
[source,java]
----
@RunWith(JUnit4.class)
public class DBUnitRulesIt {
include::../../../core/src/test/java/com/github/dbunit/rules/DBUnitRulesIt.java[tags=rules]
}
----
[discrete]
<1> https://github.com/rmpestano/dbunit-rules/blob/master/jpa/src/main/java/com/github/dbunit/rules/jpa/EntityManagerProvider.java[EntityManagerProvider^] is a simple Junit rule that creates a JPA entityManager for each test. DBunit rule don’t depend on EntityManagerProvider, it only needs a JDBC connection.
[discrete]
<2> DBUnit rule responsible for reading `@DataSet` annotation and prepare the database for each test.


******

=====
And ::
=====
The following dataset icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
.src/test/resources/dataset/yml/users.yml
----
include::../../src/test/resources/datasets/yml/users.yml[]
----


******

=====
When ::
=====
The following test is executed: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[source,java]
----
include::../../../core/src/test/java/com/github/dbunit/rules/DBUnitRulesIt.java[tags=seedDatabase]
----


******

=====
Then ::
=====
The database should be seeded with the dataset content before test execution icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
****

[[Manage-database-with-DBUnit-Rules-CDI, Manage database with DBUnit Rules CDI]]
=== *Manage database with DBUnit Rules CDI*

****
====
[quote]
____
In order to manage database state in *CDI* based tests
As a developer
I want to use DBUnit in a CDI test environment.
____
====

DBUnit CDI integration is done through a https://docs.jboss.org/weld/reference/latest/en-US/html_single/#interceptors[CDI interceptor^].

[IMPORTANT]
=====
CDI must be enabled in your test, see the following example:

[source, java]
----
@RunWith(CdiTestRunner.class) <1>
public class DBUnitCDITest {

}
----
<1> https://deltaspike.apache.org/documentation/test-control.html[CdiTestRunner^] is provided by https://deltaspike.apache.org[Apache Deltaspike^] but you should be able to use other CDI test runners.
=====
****

==== Scenario: Seed database using yml dataset

****
Given ::
=====
DBUnit interceptor is enabled in your test beans.xml: icon:thumbs-up[role="green",title="Passed"] [small right]#(634ms)#
******

[discrete]
.src/test/resources/META-INF/beans.xml
[discrete]
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://java.sun.com/xml/ns/javaee"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">
     <interceptors>
            <class>com.github.dbunit.rules.cdi.DBUnitInterceptor</class>
     </interceptors>
</beans>
----


******

[IMPORTANT]
======

Your test itself must be a CDI bean to be intercepted. if you’re using https://deltaspike.apache.org/documentation/test-control.html[Deltaspike test control^] just enable the following property in `test/resources/META-INF/apache-deltaspike.properties`:
----

deltaspike.testcontrol.use_test_class_as_cdi_bean=true
----
======

=====
And ::
=====
The following dataset icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
.src/test/resources/dataset/yml/users.yml
----
include::../../src/test/resources/datasets/yml/users.yml[]
----


******

=====
When ::
=====
The following test is executed: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[source,java]
----
include::../../src/test/java/com/github/dbunit/rules/DBUnitCDITest.java[tags=seedDatabase]
----


******

=====
Then ::
=====
The database should be seeded with the dataset content before test execution icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
****

[[Dynamic-data-using-scritable-datasets, Dynamic data using scritable datasets]]
=== *Dynamic data using scritable datasets*

****
====
[quote]
____
In order to have dynamic data in datasets
As a developer
I want to use scripts in DBUnit datasets.
____
====

Scritable datasets are backed by JSR 223.footnote:[Scripting for the Java Platform, for more information access the official https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/prog_guide/api.html[docs here^]].
****

==== Scenario: Seed database with groovy script in dataset

****
Given ::
=====
Groovy script engine is on test classpath icon:thumbs-up[role="green",title="Passed"] [small right]#(004ms)#
******

----
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-all</artifactId>
    <version>2.4.6</version>
    <scope>test</scope>
</dependency>
----


******

=====
And ::
=====
The following dataset icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

----
include::../../../core/src/test/resources/datasets/yml/groovy-with-date-replacements.yml[]
----
[discrete]
<1> Groovy scripting is enabled by `groovy:` string.


******

=====
When ::
=====
The following test is executed: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[source,java,indent=0,linenums]
----
include::../../../core/src/test/java/com/github/dbunit/rules/ScriptReplacementsIt.java[tags=groovy]
----


******

=====
Then ::
=====
Dataset script should be interpreted when seeding the database icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
****

==== Scenario: Seed database with javascript in dataset

NOTE: Javascript engine comes within JDK so no additional classpath dependency is necessary.

****
Given ::
=====
The following dataset icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

----
include::../../../core/src/test/resources/datasets/yml/js-with-calc-replacements.yml[]
----
[discrete]
<1> Javascript scripting is enabled by `js:` string.


******

=====
When ::
=====
The following test is executed: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[source,java,linenums,indent=0]
----
include::../../../core/src/test/java/com/github/dbunit/rules/ScriptReplacementsIt.java[tags=javascript-likes]
----


******

=====
Then ::
=====
Dataset script should be interpreted when seeding the database icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
****

