:toc: center
:backend: pdf
:doctitle: Living Documentation
:doctype: book
:icons: font
:numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: highlightjs
:toclevels: 3
:revnumber: 0.6.2-SNAPSHOT
:hardbreaks:

= *Living Documentation*

include::/home/pestano/projects/dbunit-rules/cdi/target/test-classes/cukedoctor-intro.adoc[leveloffset=+1]

== *Summary*
[cols="12*^m", options="header,footer"]
|===
3+|Scenarios 7+|Steps 2+|Features: 2

|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status

12+^|*<<Manage-database-with-DBUnit-Rules-Core>>*
|1
|0
|1
|4
|0
|0
|0
|0
|0
|4
|002ms
|[green]#*passed*#

12+^|*<<Manage-database-with-DBUnit-Rules-CDI>>*
|1
|0
|1
|4
|0
|0
|0
|0
|0
|4
|159ms
|[green]#*passed*#
12+^|*Totals*
|2|0|2|8|0|0|0|0|0|8 2+|161ms
|===

== *Features*

[[Manage-database-with-DBUnit-Rules-Core, Manage database with DBUnit Rules Core]]
=== *Manage database with DBUnit Rules Core*

****
====
[quote]
____
In order to manage database state in JUnit tests
As a developer
I want to use DBUnit in my tests.
____
====

DBUnit Rules Core module brings http://dbunit.sourceforge.net/[DBunit^] to your unit tests via https://github.com/junit-team/junit4/wiki/Rules[JUnit rules^].
****

==== Scenario: Seed database using yml dataset

****
Given ::
=====
The following junit rules icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
******

[discrete]
[source,java]
----
@RunWith(JUnit4.class)
public class DBUnitRulesIt {
include::../../../core/src/test/java/com/github/dbunit/rules/DBUnitRulesIt.java[tags=rules]
}
----
[discrete]
<1> https://github.com/rmpestano/dbunit-rules/blob/master/jpa/src/main/java/com/github/dbunit/rules/jpa/EntityManagerProvider.java[EntityManagerProvider^] is a simple Junit rule that creates a JPA entityManager for each test. DBunit rule don’t depend on EntityManagerProvider, it only needs a JDBC connection.
[discrete]
<2> DBUnit rule responsible for reading `@DataSet` annotation and prepare the database for each test.


******

=====
And ::
=====
The following dataset icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
.src/test/resources/dataset/yml/users.yml
----
include::../../src/test/resources/datasets/yml/users.yml[]
----


******

=====
When ::
=====
The following test is executed: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[source,java]
----
include::../../../core/src/test/java/com/github/dbunit/rules/DBUnitRulesIt.java[tags=seedDatabase]
----


******

=====
Then ::
=====
The database should be seeded with the dataset content before test execution icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
****

[[Manage-database-with-DBUnit-Rules-CDI, Manage database with DBUnit Rules CDI]]
=== *Manage database with DBUnit Rules CDI*

****
====
[quote]
____
In order to manage database state in *CDI* based tests
As a developer
I want to use DBUnit in a CDI test environment.
____
====

DBUnit CDI integration is done through a https://docs.jboss.org/weld/reference/latest/en-US/html_single/#interceptors[CDI interceptor^].

[IMPORTANT]
=====
CDI must be enabled in your test, see the following example:

[source, java]
----
@RunWith(CdiTestRunner.class) <1>
public class DBUnitCDITest {

}
----
<1> https://deltaspike.apache.org/documentation/test-control.html[CdiTestRunner^] is provided by https://deltaspike.apache.org[Apache Deltaspike^] but you should be able to use other CDI test runners.
=====
****

==== Scenario: Seed database using yml dataset

****
Given ::
=====
DBUnit interceptor is enabled in your test beans.xml: icon:thumbs-up[role="green",title="Passed"] [small right]#(158ms)#
******

[discrete]
.src/test/resources/META-INF/beans.xml
[discrete]
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://java.sun.com/xml/ns/javaee"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">
     <interceptors>
            <class>com.github.dbunit.rules.cdi.DBUnitInterceptor</class>
     </interceptors>
</beans>
----


******

[IMPORTANT]
======

Your test itself must be a CDI bean to be intercepted. if you’re using https://deltaspike.apache.org/documentation/test-control.html[Deltaspike test control^] just enable the following property in `test/resources/META-INF/apache-deltaspike.properties`:
----

deltaspike.testcontrol.use_test_class_as_cdi_bean=true
----
======

=====
And ::
=====
The following dataset icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
.src/test/resources/dataset/yml/users.yml
----
include::../../src/test/resources/datasets/yml/users.yml[]
----


******

=====
When ::
=====
The following test is executed: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[source,java]
----
include::../../src/test/java/com/github/dbunit/rules/DBUnitCDITest.java[tags=seedDatabase]
----


******

=====
Then ::
=====
The database should be seeded with the dataset content before test execution icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
****

