= DBUnit rules CDI

A CDI interceptor to configure DBUnit datasets in your tests.

[source,xml]
----
<dependency>
    <groupId>com.github.dbunit-rules</groupId>
    <artifactId>cdi</artifactId>
    <version>0.4</version>
    <scope>test</scope>
</dependency>
----

IMPORTANT: Note that since version 0.4 this module was refactored and  now it is an independent module (does not depend on *core* neither *jpa* module anymore).
This is due to CDI programing model (scopes, events, interceptors etc..) and also it was simplified and now does not support *multiple databases* which brings too much complexity to the project.

== Pre requisites

. CDI must be enabled in your tests;
+
[NOTE]
====
If you're using Deltaspike test control just enable the following
property in test/resources/META-INF/apache-deltaspike.properties:
----
   deltaspike.testcontrol.use_test_class_as_cdi_bean=true
----
====
. A jpa entity manager produced via CDI, see https://deltaspike.apache.org/documentation/jpa.html[this example^];
. Enable the following interceptor in your test beans.xml:
+
[source,xml]
----
<beans xmlns="http://java.sun.com/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">

       <interceptors>
              <class>com.github.dbunit.rules.cdi.DBUnitInterceptor</class>
       </interceptors>
</beans>
----

== Example

[source,java]
----
@RunWith(CdiTestRunner.class)
public class ContactServiceIt {

    @Inject
    DeltaSpikeContactService contactService;


    @Test
    @UsingDataSet("datasets/contacts.yml")
    public void shouldQueryAllCompanies() {
        assertNotNull(contactService);
        assertThat(contactService.findCompanies()).hasSize(4);
    }
}
----

.contacts.yml
----
contact:
  - id: 1
    name: "deltaspike"
    email: "users@deltaspike.apache.org"
    company_id: 1
  - id: 2
    name: "querydsl"
    email: "info@mysema.com"
    company_id: 2
  - id: 3
    name: "Spring"
    email: "spring@pivotal.io"
    company_id: 3

company:
  - id: 1
    name: "Apache"
  - id: 2
    name: "Mysema"
  - id: 3
    name: "Pivotal"
  - id: 4
    name: "Google"
----

Entity manager producer:

[source,java]
----
@Specializes
@ApplicationScoped
public class CdiTestConfig extends CdiConfig { <1>

   private EntityManager em;


    @Produces
    public EntityManager produce(){
      synchronized (this){
        return EntityManagerProvider.instance("customerDB").em();
      }
    }

}

----
<1> CdiConfig produces "real" entityManager

JPA persistence unit config:

.src/test/resources/META-INF/persistence.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="customerDB" transaction-type="RESOURCE_LOCAL">
        <provider>org.hibernate.ejb.HibernatePersistence</provider>

        <class>org.example.jpadomain.Company</class>
        <class>org.example.jpadomain.Contact</class>

        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.HSQLDialect" />
            <property name="javax.persistence.jdbc.driver" value="org.hsqldb.jdbcDriver" />
            <property name="javax.persistence.jdbc.url" value="jdbc:hsqldb:mem:test;DB_CLOSE_DELAY=-1" />
            <property name="javax.persistence.jdbc.user" value="sa" />
            <property name="javax.persistence.jdbc.password" value="" />
            <property name="hibernate.hbm2ddl.auto" value="create-drop" />
            <property name="hibernate.show_sql" value="true" />

        </properties>

    </persistence-unit>
</persistence>
----

